src/main/java/com/hlpp/clientcontact/domain/BrokerDealer.java
/*
 * Copyright 2007-2009 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hlpp.clientcontact.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import java.util.HashSet;
import java.util.Collection;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.annotations.Where;

/**
 * Annotation configured person bean.
 *
 * @author Casmon Gordon
 */
@Entity
@Table(name="BROKERDEALER")
public class BrokerDealer implements Serializable, Comparable<BrokerDealer> {

    private static final long serialVersionUID = -8712872385957386182L;

    private Integer id = 0;
    private Integer brokerDealerid = 0;
    private String brokerDealerName = null;
    private Integer brokerCompanyId = 0;
    private String phone = null;
    private String fax = null;
    private String contactPerson = null;
    private String status = null;
    private String notes = null;
    private Date created = null;
    private String updatedBy = null;
    private Date updateDate = null;
    private Set<BrokerDealerAddress> addresses = null;
	private Collection<ContactCase> contactCases = null;
    private Collection<DealerContact> contacts = null;
    private Collection<String> cases = null;
	private SelectionLists lists2 = null;

    /**
     * Gets id (primary key).
     */
    //@Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    public Integer getId() {
        return id;
    }

    /**
     * Sets id (primary key).
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
	 * @return the brokerDealerid
	 */
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="BROKERDEALER_ID")
	public Integer getBrokerDealerid() {
		return brokerDealerid;
	}

	/**
	 * @param brokerDealerid the brokerDealerid to set
	 */
	public void setBrokerDealerid(Integer brokerDealerid) {
		this.brokerDealerid = brokerDealerid;
	}

	/**
	 * @return the brokerDealerName
	 */
    @Column(name="BROKERDEALER_NAME")
	public String getBrokerDealerName() {
		return brokerDealerName;
	}

	/**
	 * @param brokerDealerName the brokerDealerName to set
	 */
	public void setBrokerDealerName(String brokerDealerName) {
		this.brokerDealerName = brokerDealerName;
	}

	/**
	 * @return the brokerCompanyId
	 */
    @Column(name="BROKERCOMPANY_ID")
	public Integer getBrokerCompanyId() {
		return brokerCompanyId;
	}

	/**
	 * @param brokerCompanyId the brokerCompanyId to set
	 */
	public void setBrokerCompanyId(Integer brokerCompanyId) {
		this.brokerCompanyId = brokerCompanyId;
	}

	/**
	 * @return the phone
	 */
    @Column(name="PHONE")
	public String getPhone() {
		return phone;
	}

	/**
	 * @param phone the phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * @return the fax
	 */
    @Column(name="FAX")
	public String getFax() {
		return fax;
	}

	/**
	 * @param fax the fax to set
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * @return the contactPerson
	 */
    @Column(name="CONTACT_PERSON")
	public String getContactPerson() {
		return contactPerson;
	}

	/**
	 * @param contactPerson the contactPerson to set
	 */
	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	/**
	 * @return the status
	 */
    @Column(name="STATUS")
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the notes
	 */
    @Column(name="NOTES")
	public String getNotes() {
		return notes;
	}

	/**
	 * @param notes the notes to set
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * @return the created
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * @param created the created to set
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * @return the updatedBy
	 */
    @Column(name="UPDATED_BY")
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * @param updatedBy the updatedBy to set
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * @return the updateDate
	 */
    @Column(name="UPDATED_DATE")
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * @param updateDate the updateDate to set
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

    /**
     * Gets list of <code>BrokerDealerAddress</code>es.
     */
    @OneToMany(fetch=FetchType.EAGER, cascade=CascadeType.ALL, mappedBy="clientid")
    @JoinColumn(name="CLIENT_ID")
	@Where(clause = "status != 'Deleted'")
    public Set<BrokerDealerAddress> getAddresses() {
        return addresses;
    }

    /**
     * Sets list of <code>BrokerAddress</code>es.
     */
    public void setAddresses(Set<BrokerDealerAddress> addresses) {
        this.addresses = addresses;
    }

	/**
     * Gets list of <code>ContactCase</code>es.
     */
	@Transient
    public Collection<ContactCase> getContactCases() {
        return contactCases;
    }

    /**
     * Sets list of <code>ContactCase</code>es.
     */
    public void setContactCases(Collection<ContactCase> contacts) {
        this.contactCases = contacts;
    }

	/**
     * Gets list of <code>DealerContact</code>es.
     */
	@Transient
    public Collection<DealerContact> getContacts() {
        return contacts;
    }

    /**
     * Sets list of <code>ContactCase</code>es.
     */
    public void setContacts(Collection<DealerContact> contacts) {
        this.contacts = contacts;
    }

	/**
     * Gets list of <code>Case</code>es.
     */
	@Transient
    public Collection<String> getCases() {
        return cases;
    }

    /**
     * Sets list of <code>Case</code>es.
     */
    public void setCases(Collection<String> cases) {
        this.cases = cases;
    }


	/**
     * Returns a string representation of the object.
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();

        sb.append(this.getClass().getName() + "-");
        sb.append("  id=" + id);
        sb.append("  brokerDealerName=" + brokerDealerName);
        sb.append("  phone=" + phone);
        sb.append("  fax=" + fax);
        sb.append("  contact person=" + contactPerson);
        sb.append("  created=" + created);

        return sb.toString();
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        result = prime * result + ((id == null) ? 0 : id.hashCode());

        return result;
    }

    /**
     * Indicates whether some other object is equal to this one.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final BrokerDealer other = (BrokerDealer) obj;

        if (id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!id.equals(other.id)) {
            return false;
        }

        return true;
    }


	public BrokerDealerAddress findDealerAddressById(Integer id) {
        BrokerDealerAddress result = null;

        if (addresses != null) {
            for (BrokerDealerAddress address : addresses) {
                if (address.getId().equals(id)) {
                    result = address;

                    break;
                }
            }
        }

        return result;
    }

	/**
     * Gets list of <code>SelectionLists</code>es.
     */
	@Transient
    public SelectionLists getSelectionLists() {
        return lists2;
    }

    /**
     * Sets list of <code>SelectionLists</code>es.
     */
    public void setSelectionLists(SelectionLists lists2) {
        this.lists2 = lists2;
    }

    @Override
    public int compareTo(BrokerDealer d) {
        return this.getBrokerDealerid() - d.getBrokerDealerid() ;
    }

	//@Transient
    //public boolean getHasValidAddress() {

	//	if(addresses.isEmpty()) return false;
	//	if(!addresses.isEmpty() && addresses.size() == 1){
	//		if(addresses.contains(new BrokerDealerAddress())) return false;
	//	}

	//	return true;

    //}

	@Transient
    public Set<BrokerDealerAddress> getAddressesNonEmpty() {
		if(addresses.isEmpty()){
			Set<BrokerDealerAddress> temp = new HashSet<BrokerDealerAddress>();
			temp.add(new BrokerDealerAddress());
			return temp;
		}
        return addresses;
    }


}

src/main/java/com/hlpp/clientcontact/web/controller/BrokerController.java
/*
 * Copyright 2007-2009 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hlpp.clientcontact.web.controller;

import java.util.Collection;
import java.util.Date;

import com.hlpp.clientcontact.domain.Broker;
import com.hlpp.clientcontact.domain.Person;
import com.hlpp.clientcontact.domain.ContactCase;
import com.hlpp.clientcontact.domain.BrokerContact;
import com.hlpp.clientcontact.dao.PolicyDao;
import com.hlpp.clientcontact.dao.PersonDao;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import com.hlpp.clientcontact.security.SecureUserDetails;
import org.springframework.security.core.context.SecurityContextHolder;

import javax.servlet.http.HttpServletRequest;
/**
 * Broker form controller.
 *
 * @author Casmon Gordon
 */
@Controller
public class BrokerController {

    public static final String SEARCH_VIEW_PATH_KEY = "/type/contacts";

    public static final String SEARCH_VIEW_KEY = "redirect:index.html";
    public static final String SEARCH_MODEL_KEY = "brokers";
    public static final String DETAIL_MODEL_KEY = "broker";
    public final String ACTIVE = "Active";

    @Autowired
    protected PolicyDao policyDao = null;

    @Autowired
    protected PersonDao personDao = null;


    /**
     * For every request for this controller, this will
     * create a broker instance for the form.
     */
    @ModelAttribute
    public Broker newRequest(@RequestParam(required=false) Integer id) {
        return (id != null ? policyDao.findBrokerById(id) : new Broker());
    }

    /**
     * <p>Broker form request.</p>
     *
     * <p>Expected HTTP GET and request '/broker/form'.</p>
     */
    @RequestMapping(value="/broker/form", method=RequestMethod.GET)
    public void form() {}

    /**
     * <p>Saves a broker.</p>
     *
     * <p>Expected HTTP POST and request '/broker/form'.</p>
     */
    @RequestMapping(value="/broker/form", method=RequestMethod.POST)
    public @ModelAttribute(SEARCH_MODEL_KEY) Collection<Broker> form(Broker broker, Model model) {
        if (broker.getCreated() == null) {
            broker.setCreated(new Date());
        }

        Broker result = policyDao.save(broker);

        // set id from create
        if (broker.getId() == null) {
            broker.setId(result.getId());
        }

        model.addAttribute("statusMessageKey", "broker.form.msg.success");
        return policyDao.findBrokers();
    }

    /**
     * <p>Deletes a broker.</p>
     *
     * <p>Expected HTTP POST and request '/broker/delete'.</p>
     */
    @RequestMapping(value="/broker/delete", method=RequestMethod.POST)
    public @ModelAttribute(SEARCH_MODEL_KEY) Collection<Broker> delete(Broker broker) {

		SecureUserDetails user = (SecureUserDetails)SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		Integer userid = user.getUserid();

        policyDao.delete(broker, userid);

        return policyDao.findBrokers();
    }

    /**
     * <p>Searches for all brokers and returns them in a
     * <code>Collection</code>.</p>
     *
     * <p>Expected HTTP GET and request '/broker/search'.</p>
     */
    @RequestMapping(value="/broker/search", method=RequestMethod.GET)
    public @ModelAttribute(SEARCH_MODEL_KEY) Collection<Broker> search() {
        return policyDao.findBrokers();
    }

    /**
     * <p>Searches for all brokers and returns them in a
     * <code>Collection</code>.</p>
     *
     * <p>Expected HTTP GET and request '/type/broker'.</p>
     */
    @RequestMapping(value="/type/broker_company", method=RequestMethod.GET)
    public @ModelAttribute(SEARCH_MODEL_KEY) Collection<Broker> list(HttpServletRequest request) {
		SecureUserDetails user = (SecureUserDetails)SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		request.getSession().setAttribute("user", user);
		request.getSession().setAttribute("tab_selection", "Broker");
		request.getSession().setAttribute("selectionLists", policyDao.findSelectionLists());

        return policyDao.findBrokers();
    }

    /**
     * <p>Searches for a brokers and returns it in a
     * <code>Broker</code> object.</p>
     *
     * <p>Expected HTTP GET and request '/broker/detail'.</p>
     */
    @RequestMapping(value="/broker/detail", method=RequestMethod.GET)
    public @ModelAttribute(DETAIL_MODEL_KEY) Broker display(@RequestParam("id") Integer id, @RequestParam(value="p_id", required=false) Integer p_id, Model model) {

		/*
		 * If a p_id is passed then add the person as a broker contact
		 */

		if(p_id != null){


			Collection<ContactCase> contacts = policyDao.findContactsByPersonIdAndBrokerId(p_id, id);

	        if (contacts.isEmpty()) {

				Person person = personDao.findPersonById(p_id);
				person.setBrokercompanyid(id);
				personDao.save(person);

				model.addAttribute("statusMessageKey", "contact.broker.form.msg.success");
			}else{
        		model.addAttribute("statusMessageKey", "contact.form.duplicate.type.error");
			}
		}


        Broker broker= policyDao.findBrokerById(id);
        Collection<ContactCase> contacts = policyDao.findContactsByBrokerCompanyId(id);
        Collection<BrokerContact> contacts_no_dup = policyDao.findBrokerContacts(id);
        Collection<String> cases = policyDao.findCasesByBrokerCompanyId(id);

		for (ContactCase contact : contacts) {
			contact.setCases(policyDao.findCasesByContactId(contact.getContactid()));
		}

        broker.setContactCases(contacts);
        broker.setContacts(contacts_no_dup);
        broker.setCases(cases);

        return broker;
    }

}

src/main/webapp/WEB-INF/views/jsp/broker/detail.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<head>
	<script type="text/javascript" charset="utf-8">

		function viewPerson(contactid)
		{
			 var content = document.getElementById("resultPane");
			 $.ajax({
				   type: "GET",
				   url: "view_contact.html?id="+contactid+"&type=P",  
				   
				   success: function(msg){		
											  
					   //alert(msg);
	
					   //content.innerHTML = msg;
					   $("#resultPane").html(msg);
					  
						 $("#resultPane").show().dialog({
							bgiframe: true,
							zIndex:30,
							height: 700,
							width: 900,
							modal: true,
							buttons: {								
								'Ok': function() {
									$(this).dialog('destroy');								
								}
							}
						});
					
					
						
				
					
				   },
					failure : function(msg) {
						   $("#resultPane").html(msg);
						   $("#resultPane").show().dialog({
								bgiframe: true,
								height: 100,
								width: 360,
								modal: true,
								buttons: {								
									'Ok': function() {
										$(this).dialog('destroy');								
									}
								}
							});
					
				}
			 });                       
		

		}
		
		$(document).ready(function() {
			/* Build the DataTable with third column using our custom sort functions */
			$('#contactsBCD').dataTable( {
				"bPaginate":false	
			} );
		});		
		
	</script>


</head>

<h1><fmt:message key="broker.form.title"/></h1>
<div align="left" style="padding-left:10px">
<a href='<c:url value="/type/broker_company.html"/>'>Back to Broker Company List</a>
</div>

<div id="container">
	<div id="messages">
	    <c:if test="${not empty statusMessageKey}">
	       <p><fmt:message key="${statusMessageKey}"/></p>
	    </c:if>

	    <spring:hasBindErrors name="broker">
		<h2>Errors</h2>
		<div class="formerror">
		    <ul>
		    <c:forEach var="error" items="${errors.allErrors}">
			<li>${error.defaultMessage}</li>
		    </c:forEach>
		    </ul>
		</div>
	    </spring:hasBindErrors>
	</div>
			<div class="spacer"></div>			    
			<br>
			<div id="data">
				<table cellpadding="0" cellspacing="0" border="0">
				<tr>				
				<td  width="25%"></td>
				<td width="12%"></td>
				<td width="15%"></td>
				<td width="11%"></td>
				<td width="7%"></td>
				<td width="5%"></td>
				<td width="6%"></td>
				<td width="10%"></td>
				<td  width="14%"></td>
				</tr>
					<thead> 
					<tr> 
						
						<th  class="td-header"><fmt:message key="broker.form.policies"/></th>																		
						<th  class="td-header"><fmt:message key="broker.form.brokerCompany"/></th>
						<th  class="td-header"><fmt:message key="broker.address.form.address1"/></th>						
						<th  class="td-header"><fmt:message key="broker.address.form.address2"/></th>						
						<th  class="td-header"><fmt:message key="broker.address.form.city"/></th>												
						<th  class="td-header"><fmt:message key="broker.address.form.state"/></th>												
						<th  class="td-header"><fmt:message key="broker.address.form.zipPostal"/></th>												
						<th  class="td-header"><fmt:message key="broker.form.primaryPhone"/></th>
						<th  class="td-header"><fmt:message key="broker.form.primaryFax"/></th>
					</tr> 
					</thead> 
					<tbody> 


					<c:set var="display" value="true" />
					<c:forEach var="address" items="${broker.addressesNonEmpty}" varStatus="status">										
					<tr> 	
						<c:if test="${display=='true'}">					
							<td class="td-plain_">
								<c:forEach var="case" items="${broker.cases}">
									${case},
								</c:forEach>
							</td>
						</c:if>
						<c:if test="${display!='true'}">						
							<td class="td-plain_">&nbsp;</td> 													
						</c:if>						
						<td class="td-plain_">${broker.brokerCompany}</td> 							
						<td class="td-plain_">${address.address1}</td>
						<td class="td-plain_">${address.address2}</td>
						<td class="td-plain_">${address.city}</td>
						<td class="td-plain_">${address.state}</td>
						<td class="td-plain_">${address.zipPostal}</td>
						<td class="td-plain_">${broker.primaryPhone}</td>
						<td class="td-plain_">${broker.primaryFax}</td>
						
						<c:set var="display" value="false" />																
					<tr> 
					</c:forEach>							

					</tbody> 
				</table> 	
				<br>
				<table width="100%">
				<tr>
					<td width="25%" class="td-plain" align="right"><fmt:message key="broker.form.notes"/>:</td>
					<td class="td-plain_" colspan="8"><form:textarea path="broker.notes" disabled="true" rows="5" cols="85" style="width:100%"/></td>
				</tr>
				</table>			
			</div>

			<br>
			
			<div style="float:left; width:100%;padding: 1.5ex 1ex 1ex 1.5mm;">			
				<div class="full_width big">
					<c:if test="${user.department=='Compliance'}">							
					    <sec:authorize ifAnyGranted="ROLE_WRITE,ROLE_ADMIN">
						    <c:url var="createUrl" value="/type/contacts_select.html">
							<c:param name="type" value="B" />
							<c:param name="flow_id" value="${broker.brokerid}" />						
							<c:param name="flow_desc" value="${broker.brokerCompany}" />																	
						    </c:url>
						    <a href='<c:out value="${createUrl}"/>'><img src="/contacts/images/add.png" width="20" border="0" title="Click to add contact"><fmt:message key="button.create.contact"/></a> 					    
					    </sec:authorize>
					</c:if>    
				</div>
			</div>									
			<br>	

			<div class="spacer"></div>
			
			<c:forEach var="contact" items="${broker.contacts}" varStatus="status">					

			    <c:set var="personFormId" value="contact${status.index}"/>							 

			    <sec:authorize ifAnyGranted="ROLE_WRITE,ROLE_ADMIN">
				<c:url var="deleteUrl" value="/broker_person/delete.html"/>			    
				<form id="${personFormId}" action="${deleteUrl}" method="POST">
				  <input id="id" name="id" type="hidden" value="${contact.contactid}"/>
		  		  <input id="flow_id" name="flow_id" type="hidden" value="${broker.brokerid}"/>				  
		  		  <input id="type" name="type" type="hidden" value="B"/>		  				  		  		  
				</form>
			    </sec:authorize>

			</c:forEach>			
			
			
			<div id="data">			
				<div style="float:left; width:100%;padding: 1.5ex 1ex 1ex 1.5mm;">
					<table cellpadding="0" cellspacing="0" border="0" class="display" id="contactsBCD">
						<thead> 
						<tr> 
							<th align="left">&nbsp;</th>																				
							<th width="22%" align="left"><fmt:message key="broker.contact.name"/></th>				
							<th width="10%" nowrap align="left"><fmt:message key="broker.contact.typeofcontact"/></th>
							<th align="left"><fmt:message key="broker.contact.policies"/></th>
							<th align="left">&nbsp;</th>														
						</tr> 
						</thead> 
						<tbody> 
							<c:forEach var="contact" items="${broker.contacts}" varStatus="status">					
							    
							    <c:set var="personFormId" value="contact${status.index}"/>							 

							    <c:url var="editUrl" value="/person.html">
							        <c:param name="id" value="${contact.contactid}" />
							        <c:param name="type" value="B" />							    							        
								<c:param name="flow_id" value="${broker.brokerid}" />													        
							    </c:url>
							
							    <tr>
								<td>
									<input type="button" value="Preview" class="greyButton" onClick='javascript:viewPerson("${contact.contactid}")'/>						
								</td>								
								<td><b><a href='<c:out value="${editUrl}"/>' title="Click to edit person">${contact.contactName}</b></a><br>${contact.companyName}</td> 							
								<td>${contact.contactType}</td> 							
								<td style="line-height:15px">${contact.casecodes}</td>
								<td>
								<c:if test="${user.department=='Compliance'}">			
								    <sec:authorize ifAnyGranted="ROLE_WRITE,ROLE_ADMIN">
								    	<input type="button" value="Delete" class="greyButton" onClick="javascript:delete_item_custom(document.forms['${personFormId}'], 'BROKER_CONTACT');"/>								    
								    </sec:authorize> 
								</c:if>
								</td>								
							    </tr>
							</c:forEach>
						</tbody> 
					</table> 			
				</div>			
			</div>

</div>			
<div id="resultPane" title="Contact Preview"></div>


src/main/webapp/WEB-INF/views/jsp/broker/search.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>

<h1><fmt:message key="broker.search.title"/></h1>

<table class="search">
    <tr>
	<th><fmt:message key="broker.form.brokerCompany"/></th>
	<th><fmt:message key="broker.form.primaryPhone"/></th>
	<th><fmt:message key="broker.form.primaryFax"/></th>
	<th><fmt:message key="broker.form.secondaryPhone"/></th>
	<th><fmt:message key="broker.form.secondaryFax"/></th>
	<th><fmt:message key="broker.form.status"/></th>						
	<th><fmt:message key="broker.form.updatedBy"/></th>						
	<th><fmt:message key="broker.form.updateDate"/></th>
    </tr>
<c:forEach var="broker" items="${brokers}" varStatus="status">
    <tr>
        <c:set var="brokerFormId" value="broker${status.index}"/>

        <c:url var="editUrl" value="/broker.html">
            <c:param name="id" value="${broker.brokerId}" />
        </c:url>
        
        <sec:authorize ifAnyGranted="ROLE_WRITE,ROLE_ADMIN">
            <c:url var="deleteUrl" value="/broker/delete.html"/>
            <form id="${brokerFormId}" action="${deleteUrl}" method="POST">
                <input id="id" name="id" type="hidden" value="${broker.brokerId}"/>
            </form>
        </sec:authorize>

	<td><a href='<c:out value="${editUrl}"/>'>${broker.brokerCompany}</a></td> 							
	<td>${broker.primaryPhone}</td>
	<td>${broker.primaryFax}</td>
	<td>${broker.secondaryPhone}</td>
	<td>${broker.secondaryFax}</td>
	<td>${broker.status}</td>
	<td>${broker.updatedBy}</td>							
	<td>${broker.updateDate}</td>														
    	<td>
            <a href='<c:out value="${editUrl}"/>'><fmt:message key="button.edit"/></a>
            <sec:authorize ifAnyGranted="ROLE_WRITE,ROLE_ADMIN">
                <a href="javascript:delete_item(document.forms['${brokerFormId}']);"><fmt:message key="button.delete"/></a> 
            </sec:authorize>
        </td>
    </tr>
</c:forEach>
</table>